# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a211073e0df70b1bc7a35e1f220c23af43ebc449f45585ace1575fe44dab37c7cd57e4e8ca611a4fbfadfd5abfb74c767ed71f09e4e4c1f22fbb798877e68a21

test:
  secret_key_base: f64bda0a7b2744619f40998cb9cef77f62b5ac23d215f18e0cd8ca9b85d501c524ef6e998ae4446404114a2d0c616f9c79143ce5e4b5fbd6ba7a9d17c865c3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
